# numpy

In [2]:
import sys
import numpy as np

## Basic Numpy Arrays

In [6]:
a = np.array([1,2,3,4,5,6])
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], b[0]

(np.int64(1), np.float64(0.0))

In [14]:
a[0:]

array([1, 2, 3, 4, 5, 6])

In [21]:
a[1:3]

array([2, 3])

In [26]:
a[0:-1]

array([1, 2, 3, 4, 5])

In [38]:
# a[start:stop:step]
a[1::2]

array([2, 4, 6])

In [39]:
a[0], a[2]

(np.int64(1), np.int64(3))

In [40]:
a[[0,2]]

array([1, 3])

## Array Types

In [41]:
a.dtype

dtype('int64')

In [43]:
np.array([4,5,6,7], dtype=np.float64)

array([4., 5., 6., 7.])

In [44]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

## Dimenson Shape

In [46]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [47]:
A.shape

(2, 3)

In [50]:
A.size

6

In [51]:
A.ndim

2

In [49]:
A[1:, 2:]

array([[6]])

In [60]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]

    ],
    [
        [6, 5, 4],
        [3, 2, 1]

    ]
])

In [61]:
B.size

24

In [62]:
B.shape

(4, 2, 3)

In [63]:
B[3:, 1:, 2:]

array([[[1]]])

In [64]:
B.ndim

3

In [65]:
b.dtype

dtype('float64')

In [66]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [67]:
A[1][0]

np.int64(4)

## Statistics

In [68]:
a = np.array([1,2,3,4,5,6,7,89])

In [69]:
a.sum()

np.int64(117)

In [70]:
a.mean()

np.float64(14.625)

In [72]:
a.std()

np.float64(28.173291873687745)

In [73]:
a.var()

np.float64(793.734375)

## Broadcasting and Vectorized operations

In [76]:
a = np.arange(10)

In [77]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [79]:
a += 100

In [80]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [81]:
[ a* 10]

[array([1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090])]

In [82]:
[ a + 10 for i in a]

[array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]),
 array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119])]

## Boolean

In [83]:
a = np.arange(10)

In [84]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a >= 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# Das ~ ist der bitweise NOT-Operator (Negation für Booleans):
# ~[False, False, False, True, True]
#  [True, True, True, False, False]

# Das bedeutet: Gib alle Elemente zurück, die nicht größer als der Mittelwert sind.
a[~(a > a.mean())]


array([0, 1, 2, 3, 4])

# Lieare Algebra

In [87]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [88]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [89]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [90]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [93]:
# np.dot(B, A) # Dotprodukt

In [94]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [95]:
%time np.sum(a ** 2)

CPU times: user 35 μs, sys: 3 μs, total: 38 μs
Wall time: 40.5 μs


np.int64(285)

In [97]:
%time sum([x ** 2 for x in a])

CPU times: user 15 μs, sys: 1e+03 ns, total: 16 μs
Wall time: 17.9 μs


np.int64(285)

## Numpy Random

In [98]:
np.random.random(size=20)

array([0.38256686, 0.44645136, 0.96410085, 0.96276656, 0.24970316,
       0.8777869 , 0.49450918, 0.18287762, 0.99843413, 0.33473566,
       0.83351357, 0.10088723, 0.74816466, 0.26189208, 0.57740805,
       0.92176124, 0.05590183, 0.00999163, 0.99141804, 0.9121921 ])

In [ ]:
np.random.normal(size=2) #  zwei Zufallszahlen aus einer normalverteilten (gaußschen) Verteilun

array([-1.65337869,  0.13334758])