In [1]:
import numpy as np
from numpy.linalg import svd

# Beispiel: Nutzer-Bewertungsmatrix (Zeile: Nutzer, Spalte: Film)
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [0, 0, 5, 4],
    [0, 1, 5, 4],
], dtype=float)

# Schritt 1: Führe SVD durch
U, S, VT = svd(R, full_matrices=False)

# Schritt 2: Wähle die Top-k Komponenten (Reduktion)
k = 2  # Wir behalten nur die 2 wichtigsten "Features"
U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

# Schritt 3: Rekonstruiere die Matrix mit reduzierter Dimension
R_approx = np.dot(U_k, np.dot(S_k, VT_k)) # np.dot = A @ A Beispiel

# Ergebnis anzeigen
print("Original Matrix (mit Lücken):\n", R)
print("\nRekonstruierte Matrix (mit Vorhersagen):\n", np.round(R_approx, 2))


Original Matrix (mit Lücken):
 [[5. 3. 0. 1.]
 [4. 0. 0. 1.]
 [1. 1. 0. 5.]
 [0. 0. 5. 4.]
 [0. 1. 5. 4.]]

Rekonstruierte Matrix (mit Vorhersagen):
 [[ 5.08  2.09 -0.59  1.68]
 [ 3.34  1.38 -0.34  1.16]
 [ 1.88  1.07  2.07  2.99]
 [-0.38  0.41  4.48  4.46]
 [-0.07  0.54  4.46  4.58]]


In [2]:
R_approx

array([[ 5.07935709,  2.09170657, -0.5895779 ,  1.68287709],
       [ 3.33973739,  1.38156122, -0.33886418,  1.15693483],
       [ 1.87945991,  1.06667215,  2.070676  ,  2.9881331 ],
       [-0.38045278,  0.41021775,  4.47707493,  4.45522948],
       [-0.06608127,  0.54214237,  4.45985831,  4.57930469]])

In [3]:
U

array([[-0.24097949, -0.7609249 ,  0.25822011,  0.49915279],
       [-0.16527424, -0.49770817,  0.14302455, -0.79333348],
       [-0.40945058, -0.15916667, -0.89806074,  0.0193043 ],
       [-0.60226225,  0.29403493,  0.22558572, -0.24721238],
       [-0.61987395,  0.24797038,  0.23550869,  0.24491194]])

In [4]:
U_k

array([[-0.24097949, -0.7609249 ],
       [-0.16527424, -0.49770817],
       [-0.40945058, -0.15916667],
       [-0.60226225,  0.29403493],
       [-0.61987395,  0.24797038]])

In [5]:
S

array([9.9746788 , 6.90131816, 3.36122829, 1.89201874])

In [6]:
S_k

array([[9.9746788 , 0.        ],
       [0.        , 6.90131816]])

In [7]:
VT

array([[-0.22812213, -0.17567112, -0.61261933, -0.73606896],
       [-0.86282413, -0.31790608,  0.39268245,  0.01645408],
       [ 0.28713849,  0.03335337,  0.68590167, -0.6678158 ],
       [-0.34791709,  0.93110845, -0.00607933, -0.10933345]])

In [8]:
VT_k

array([[-0.22812213, -0.17567112, -0.61261933, -0.73606896],
       [-0.86282413, -0.31790608,  0.39268245,  0.01645408]])

In [9]:
import numpy as np

# Beispiel: Original mit Lücken (0 = keine Bewertung)
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [0, 0, 5, 4],
    [0, 1, 5, 4],
], dtype=float)

# SVD
U, S, VT = np.linalg.svd(R, full_matrices=False)
k = 2  # z. B. Top-2-Komp.
U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

# Rekonstruierte Matrix
R_pred = U_k @ S_k @ VT_k

# Empfehlung für Nutzer B (Index 1)
user_index = 1
original_ratings = R[user_index]
predicted_ratings = R_pred[user_index]

# Finde nur Filme, die Nutzer B **nicht bewertet** hat
unrated_indices = np.where(original_ratings == 0)[0]

# Empfehlungen: sortiert nach vorhergesagtem Wert
recommendations = sorted(
    [(i, predicted_ratings[i]) for i in unrated_indices],
    key=lambda x: x[1],
    reverse=True
)

# Ausgabe
print("Empfehlung für Nutzer B:")
for film_index, score in recommendations:
    print(f"Film {film_index + 1} mit geschätzter Bewertung: {score:.2f}")


Empfehlung für Nutzer B:
Film 2 mit geschätzter Bewertung: 1.38
Film 3 mit geschätzter Bewertung: -0.34


In [10]:
import numpy as np

# Bewertungsmatrix (Nutzer x Filme)
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [0, 0, 5, 4],
    [0, 1, 5, 4],
], dtype=float)


In [11]:
# Volle SVD-Zerlegung
U, S, VT = np.linalg.svd(R, full_matrices=False)

# Wähle nur Top-2 Komponenten (k = 2)
k = 2
U_k = U[:, :k]         # Nutzer-Vektoren (5 Nutzer, 2 Themen)
S_k = np.diag(S[:k])   # Diagonalmatrix mit Top-2 Singulärwerten
VT_k = VT[:k, :]       # Filme (2 Themen, 4 Filme)


In [12]:
np.set_printoptions(precision=2, suppress=True)  # schönere Anzeige

print("U_k (Nutzer im latenten Raum):")
print(U_k)

print("\nS_k (Wichtigkeit der Themen – Singulärwerte):")
print(S_k)

print("\nVT_k (Filme im latenten Raum – transponiert):")
print(VT_k)


U_k (Nutzer im latenten Raum):
[[-0.24 -0.76]
 [-0.17 -0.5 ]
 [-0.41 -0.16]
 [-0.6   0.29]
 [-0.62  0.25]]

S_k (Wichtigkeit der Themen – Singulärwerte):
[[9.97 0.  ]
 [0.   6.9 ]]

VT_k (Filme im latenten Raum – transponiert):
[[-0.23 -0.18 -0.61 -0.74]
 [-0.86 -0.32  0.39  0.02]]


In [15]:
term1 = -0.24 * 9.97 * -0.61 = 1.460
term2 = -0.76 * 6.9 *  0.39 = -2.045

rating = term1 + term2
rating


SyntaxError: cannot assign to expression (3007564317.py, line 1)