In [1]:
import numpy as np

In [2]:
A = np.array([[1,2], [3,4]])  
B = np.array([[5,6], [7,8]]) 

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
B

array([[5, 6],
       [7, 8]])

In [8]:
# Matrix multiplication
print(A @ B)

[[19 22]
 [43 50]]


In [9]:
import numpy as np

def simple_svd(A):
    # 1. Berechne A^T A und A A^T
    ATA = A.T @ A
    AAT = A @ A.T

    # 2. Eigenzerlegung
    eigvals_V, V = np.linalg.eigh(ATA)  # V: Spalten sind Eigenvektoren von ATA
    eigvals_U, U = np.linalg.eigh(AAT)  # U: Spalten sind Eigenvektoren von AAT

    # 3. Sortiere Eigenwerte & Vektoren (absteigend)
    sorted_indices = np.argsort(eigvals_V)[::-1]
    eigvals_V = eigvals_V[sorted_indices]
    V = V[:, sorted_indices]

    sorted_indices_U = np.argsort(eigvals_U)[::-1]
    eigvals_U = eigvals_U[sorted_indices_U]
    U = U[:, sorted_indices_U]

    # 4. Berechne Singulärwerte (Wurzel aus Eigenwerten von A^T A)
    singular_values = np.sqrt(np.maximum(eigvals_V, 0))  # gegen negative Rundungsfehler schützen

    # 5. Baue Sigma-Matrix (Diagonalmatrix)
    m, n = A.shape
    Sigma = np.zeros((m, n))
    for i in range(min(m, n)):
        Sigma[i, i] = singular_values[i]

    return U, Sigma, V.T


In [10]:
A = np.array([
    [5, 0],
    [3, 1],
    [0, 4]
], dtype=float)

U, Sigma, VT = simple_svd(A)

print("U:\n", np.round(U, 2))
print("\nSigma:\n", np.round(Sigma, 2))
print("\nV^T:\n", np.round(VT, 2))

# Rekonstruktion testen
A_reconstructed = U @ Sigma @ VT
print("\nRekonstruierte A:\n", np.round(A_reconstructed, 2))


U:
 [[-0.84 -0.21  0.5 ]
 [-0.53  0.12 -0.84]
 [-0.11  0.97  0.21]]

Sigma:
 [[5.87 0.  ]
 [0.   4.06]
 [0.   0.  ]]

V^T:
 [[-0.99 -0.17]
 [ 0.17 -0.99]]

Rekonstruierte A:
 [[ 4.71  1.66]
 [ 3.16  0.06]
 [ 1.33 -3.77]]


In [11]:
def better_svd(A, k=None):
    # Schritt 1: Eigenzerlegung von A^T A
    ATA = A.T @ A
    eigvals, V = np.linalg.eigh(ATA)

    # Sortieren (absteigend)
    idx = np.argsort(eigvals)[::-1]
    eigvals = eigvals[idx]
    V = V[:, idx]

    # Singulärwerte berechnen
    singular_values = np.sqrt(np.maximum(eigvals, 0))

    # Falls k gegeben, auf Top-k begrenzen
    if k is not None:
        singular_values = singular_values[:k]
        V = V[:, :k]

    # U berechnen: U_i = (1/σ_i) * A * V_i
    U = np.zeros((A.shape[0], len(singular_values)))
    for i in range(len(singular_values)):
        if singular_values[i] > 1e-10:
            U[:, i] = A @ V[:, i] / singular_values[i]

    # Sigma bauen
    Sigma = np.zeros((U.shape[1], V.shape[1]))
    np.fill_diagonal(Sigma, singular_values)

    return U, Sigma, V.T


In [12]:
A = np.array([
    [5, 0],
    [3, 1],
    [0, 4]
], dtype=float)

U, Sigma, VT = better_svd(A)

print("U:\n", np.round(U, 2))
print("\nSigma:\n", np.round(Sigma, 2))
print("\nV^T:\n", np.round(VT, 2))

# Rekonstruktion
A_recon = U @ Sigma @ VT
print("\nRekonstruierte A:\n", np.round(A_recon, 2))


U:
 [[-0.84  0.21]
 [-0.53 -0.12]
 [-0.11 -0.97]]

Sigma:
 [[5.87 0.  ]
 [0.   4.06]]

V^T:
 [[-0.99 -0.17]
 [ 0.17 -0.99]]

Rekonstruierte A:
 [[ 5. -0.]
 [ 3.  1.]
 [ 0.  4.]]


In [14]:
# SVD with numpy

import numpy as np
from numpy.linalg import svd

# Beispielmatrix: 3 Nutzer, 2 Filme
A = np.array([
    [5, 0],
    [3, 1],
    [0, 4]
], dtype=float)

U, S, VT = svd(A, full_matrices=False)

In [15]:
U

array([[-0.83886765,  0.20790743],
       [-0.53205897, -0.11800657],
       [-0.11495354, -0.97100409]])

In [16]:
S

array([5.87485133, 4.06031056])

In [20]:
Sigma = np.diag(S)
Sigma

array([[5.87485133, 0.        ],
       [0.        , 4.06031056]])

In [17]:
VT

array([[-0.98564454, -0.16883374],
       [ 0.16883374, -0.98564454]])

In [21]:
A_re = U @ Sigma @ VT
A_re

array([[ 5.00000000e+00, -5.73053513e-16],
       [ 3.00000000e+00,  1.00000000e+00],
       [-1.11022302e-16,  4.00000000e+00]])